name: Build and Push Multi-Architecture Docker Image (Latest Build)

on:
  push:
    branches:
      - main
    paths:
      - 'src/garmin_grafana/garmin_fetch.py'
      - 'src/garmin_grafana/__init__.py'
      - 'compose-example.yml'
      - 'pyproject.toml'
      - 'Dockerfile'
      - '.python-version'
      - 'uv.lock'

env:
  IMAGE_NAME: garmin-fetch-data
  IMAGE_TAG: latest
  IMAGE_REPO: thisisarpanghosh

jobs:
  build_and_push:
    name: Build Multi-Arch Docker Image and Push to Docker Hub & GHCR
    if: ${{ github.repository == 'arpanghosh8453/garmin-grafana' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for Multi-Architecture Support
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Multi-Arch Image (linux/amd64, linux/arm64) and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

        
